.github/workflows/tests.yml, nextjs/src/app/(marketing)/feedback/page.tsx, nextjs/src/app/(marketing)/layout.tsx, nextjs/src/app/globals.css, nextjs/src/components/marketing/FeedbackBanner.tsx, nextjs/tailwind.config.ts
This PR adds a banner that displays a feedback form that submits feedback to a Posthog survey
It also has links to Mapped v1 and the about oage
Addresses issue [MEEP-266](https://linear.app/commonknowledge/issue/MEEP-266/add-a-test-software-banner-with-a-feedback-request-button)
Download the branch and run locally 
Navigate to home page and observe the banner on page load
Click on submit feedback button
Fill out the feedback form
Navigate to Posthog and observe the response under the survey
https://us.posthog.com/project/19510/surveys/018ebe3a-d763-0000-a3b2-aac0beec82fa
Standard continuous deployment
=> add banner that requests feedback to marketing pages

hub/graphql/mutations.py
This PR replaces the timestamp that was the previous default report name with some text 'Type your report name here'
Addresses issue [MEEP-309](https://linear.app/commonknowledge/issue/MEEP-309/generate-a-nice-random-report-name)
Download branch and run locally
Navigate to http://localhost:3000/reports and click create new report
Observe the new default name
=> Add nicer default name to reports

.github/workflows/build.yml, .github/workflows/tests.yml, hub/migrations/0115_alter_mailchimpsource_unique_together.py, poetry.lock, pyproject.toml
Upgrades the procrastinate version to 2.3
The worker was no longer starting on render, due to faulty psycopg detection.
Start up the app, create some jobs (e.g. import a data source), and check the worker
correctly executes the jobs.
Normal deployment.
=> feat: upgrade procrastinate to fix psycopg issues

hub/cache_keys.py, hub/graphql/types/model_types.py, hub/models.py, hub/views/vector_tiles.py, utils/url.py
Adds data filtering support for hubs.
- Adds `filter` key to the `MapLayer` dict
- Implements data source (GenericData) filtering for hub tile / graphql queries
This PR doesn't handle filtering for private reports.
TCC wants to display only events that have been published on the public map. This PR adds filtering logic at the level of the hub.
An alternative approach might have been to add filtering logic at the level of the external data source, to apply to all queries — including private reports — but that seemed too presumptuous. Private reports might have their own filtering logic.
- Add a filter key to the layer
- Look at the hub map and note whether the markers and event listings comply
N/A
=> Hub maps can have arbitrary layer filters (e.g. only published=true)

hub/management/commands/import_2024_ppcs.py, hub/tasks.py
Adds a Procrastinate task on the hour to refresh PPCs.
Also assigns them to a separate queue. For now, we have one worker that runs tasks regardless of queue. In future, we might want to divvy this out. [See Procrastinate docs.](https://procrastinate.readthedocs.io/en/stable/howto/basics/worker.html#launch-a-worker)
=> Refresh PPCs every hour

hub/models.py, hub/views/vector_tiles.py
When the repo has just been installed, Wagtail adds a default Site and root page. This PR prevents the tilserver from erroring out in that situation.
=> When there are no sites, the tile json API should still work

hub/tests/test_sources.py, nextjs/src/middleware.ts
Fix front-end sentry logging. The internal sentry requests were being blocked by our middleware.
=> fix: prevent middleware blocking sentry requests

.flake8, hub/graphql/types/model_types.py
So that reports will still load even if the data source has been removed. Then the user can modify them, instead of the page crashing.
=> feat: ignore map layers with missing sources

hub/graphql/extensions/analytics.py, hub/graphql/extensions/api_blacklist.py, hub/tests/test_source_parser.py, utils/py.py
Our date parsing was assuming an American formatted date when valid (e.g. 1/2/2024 was 2nd of January 2024) 🤢
=> fix: limit date parsing to en-GB locales

Dockerfile, hub/graphql/schema.py, hub/models.py, local_intelligence_hub/settings.py, nextjs/src/app/(app)/data-sources/create/connect/[externalDataSourceType]/page.tsx, nextjs/src/app/(auth)/account/verify/page.tsx, nextjs/src/components/hub/EventCard.tsx
- Event dates were being parsed in UTC but formatted in local time. They either need to be parsed in the correct timezone and formatted in local time, or parsed and formatted in the same timezone. The latter was easier, so that's what is done here.
- The Docker container seemed to need `python3-dev` to install `libsass` in the dev container.
=> fix: event date formatting, poetry install in devcontainer

hub/enrichment/sources/__init__.py
This allows the user to select the address picker when they map data across to a third party data source.
In some situations, a postcode has ambiguous polling stations. In other implementations of this data set, the user is shown a dropdown so they can choose their specific address. We obviously can't do that when writing data across, so need to just allow CRMs to know this so they can show the user another path to find out their polling location.
See https://api.electoralcommission.org.uk/docs/endpoints/#postcode-search-results-found-3 for a situation where results are found.
See https://api.electoralcommission.org.uk/docs/endpoints/#postcode-search-address-picker-3 for a situation where a data picker is displayed.
It is useful to know this in, say, Action Network, to make decisions on …
=> MAP-434 - Surface Address Picker In Data Mapping 

hub/fixtures/areas.json, hub/graphql/types/model_types.py, hub/management/commands/import_mps.py, hub/tests/test_import_mps.py, hub/tests/test_views.py, nextjs/src/components/reportsConstituencyItem.tsx
Updates the `import_mps` command to link MPs to the 2024 constituency `Areas`.
Checkout the branch. Run `python manage.py import_mps`. Check the correct MP is visible
in the report.
Need to run the above command after deployment. We may need to delete existing MPs first.
=> feat: import 2024 MPs

nextjs/src/app/hub/render/[hostname]/map/SearchPanel.tsx, nextjs/src/app/hub/render/[hostname]/map/page.tsx, nextjs/src/components/hub/ConstituencyView.tsx
This PR passes the search input value into the query string for Loudspeek
https://peopleclimatenature.onldspk.cc/2024-mps/frame/write
This is because for some postcodes samplePostcode was null in the constituency data that was being returned from the API.
As we are only using it for Loudspeek it seemed worthwhile to simplify this. 
Addresses issue [CC-185](https://linear.app/commonknowledge/issue/CC-185/there-is-an-additional-step-in-the-e-action-for-some-postcodes)
Download the branch and run locally
Go to the map page and search by postcode e.g. http://hub.localhost:3000/map?postcode={postcode}
Test the following postcodes and observe that they return the MP straight away rather than an intermediate search being needed (unlike on the live site)
BA2 8LZ 
BA10 0JW
YO42 4TR
Normal …
=> Pass postcode to Loudspeek e-action form from search form input 

nextjs/package-lock.json, nextjs/package.json, nextjs/src/data/puck/config/blocks/RichText/customRichTextStyles.css, nextjs/src/data/puck/config/blocks/RichText/index.tsx, nextjs/src/data/puck/config/index.tsx
This PR 
- removes a unnecessary Text Block that was crashing the editor
- adds a custom Rich Text component using React Quill 
Addresses issue [CC-187](https://linear.app/commonknowledge/issue/CC-187/cannot-edit-richtext-block-in-puck-editor)
There was a bug with the existing [Puck Rich Text Component](https://www.npmjs.com/package/@tohuhono/puck-rich-text)(details are in the Linear ticket)
Download the branch and run locally
Navigate http://localhost:3000/hub/editor/ 
Add a RichText block to the page
Apply styles to the text
Publish and see on the page
Normal deployment process
=> Add rich text editor puck cms

nextjs/src/app/hub/render/[hostname]/map/SearchPanel.tsx, nextjs/src/app/hub/render/[hostname]/map/page.tsx, nextjs/src/components/hub/ConstituencyView.tsx, nextjs/src/data/puck/config/root.tsx
A very simple implementation of the design here: https://www.figma.com/proto/kxiLho8sEr4YRyyS5DjrhD/Climate-Coalition-2024-Election-Hub-(Post-Launch-Design)?page-id=3136%3A1586&node-id=3136-1990&node-type=canvas&viewport=720%2C218%2C0.07&t=ewfvCrZ0AqAHJZCQ-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3136%3A1990&show-proto-sidebar=1&hide-ui=1
To get something out fast!
It just scrolls:
=> feat: display hub map on mobile

.devcontainer/devcontainer.json
This PR adds a mounts configuration to the dev container set up to allow the container to access SSH keys on the host machine e.g. for authenticating with GitHub
Addresses issue [MAP-586](https://linear.app/commonknowledge/issue/MAP-586/fix-ssh-authentication-with-github-in-dev-container)
Download the branch and run locally
Rebuild the container if prompted
Run `ssh -T git@github.com` inside the container to test connection to GitHub
You should see a message like this
Hi <username>! You've successfully authenticated, but GitHub does not provide shell access.
=> Make host machine ssh keys available to dev container 

nextjs/package-lock.json, nextjs/package.json, nextjs/src/components/navbar.tsx, nextjs/src/components/puck/config/blocks/GridRow/index.tsx, nextjs/src/components/ui/alert.tsx, nextjs/src/components/ui/button.tsx, nextjs/src/components/ui/label.tsx, nextjs/src/components/ui/sheet.tsx, nextjs/src/components/ui/toggle.tsx, nextjs/src/lib/utils.ts
`@trivago/prettier-plugin-sort-imports` doesn't remove unused imports. 
This PR reverts to `prettier-plugin-organize-imports`
=> Revert broken prettier config change

hub/graphql/mutations.py, nextjs/src/app/(logged-in)/reports/ReportList/CreateReportCard.tsx, nextjs/src/app/reports/[id]/(components)/MapLayers/PoliticalChoropleths.tsx, nextjs/src/app/reports/[id]/addCountByGssToMapboxLayer.ts, nextjs/src/app/reports/[id]/mapboxStyles.ts, nextjs/src/app/reports/[id]/useBoundaryAnalytics.ts
Follows on from #147.
- Re-adds area names and labels which was in the old map
- Adds some stronger typing the to the Boundary Analytics hook return data
=> Revive area labels counts [MAP-661]

.vscode/launch.json, hub/management/commands/runworker.py, poetry.lock, pyproject.toml
Adds the command, and updates the run configuration to use this instead of the underlying `procrastinate worker` command.
When developing Mapped, it's very annoying to have to remember to restart the worker when changing background job code.
1. Start the run configuration "Django background worker" (or "Run Mapped!")
2. Wait for the worker to start up (`Launching a worker on all queues`)
3. Toggle the log level of `procrastinate.worker` in `local_intelligence_hub/settings.py` from `INFO` to `DEBUG` (or vice versa)
4. Observe that the worker restarts. If the log level is `DEBUG`, there should be `procrastinate.worker.wait_for_job:172 # Waiting for new jobs on all queues` log statements. If the log level is `INFO`, there should not be.
You can also check that breakpoints work in the job …
=> feat: adds runworker command that will restart the worker on code changes

nextjs/src/app/(logged-in)/data-sources/create/connect/[externalDataSourceType]/page.tsx
This PR adds the following:
1. Airtable Base and Table IDs are extracted from the url for the Airtable base
2. Action Network group slug is extracted from the url for the Action Network group
3. Google Sheets id is extracted from  the Google Sheets URL
4. Google Sheets connected fetches the sheet names and puts them in a dropdown
Addresses issues [MAP-671](https://linear.app/commonknowledge/issue/MAP-671/auto-extract-sheet-id-and-sheet-name-for-google-sheet) and [MAP-670](https://linear.app/commonknowledge/issue/MAP-670/auto-extract-group-slug-from-action-network-url)
Run the branch locally
Go through the add data source flows for Airtable, Action Network and Google Sheets
To authenticate a Google Sheet you'll need to run the frontend server with `npm run https`
=> Improving data onboarding flow across Action Network, Google Sheets and Airtable [MAP-670] [MAP-671]

nextjs/src/app/reports/[id]/(components)/ReportNavbar.tsx
This PR adds a button to toggle the left sidebar on the map page
Addresses issue [MAP-675](https://linear.app/commonknowledge/issue/MAP-675/make-the-sidebar-collapsible)
[Figma](https://www.figma.com/design/Z8P0RWUpZdeoFvkTrKIGjm/Mapped%3A-Hope-Not-Hate?node-id=4334-67083&t=AzPc2iaTtQWtvfZ0-0)
Download the branch and run locally
Create a map or navigate to an existing map page
Click on the sidebar panel icon in the top navbar
Observe the sidebar collapses in and out of view
Normal deployment process
=> Make left sidebar toggle on map page

nextjs/src/app/reports/[id]/(components)/ReportVisualisation.tsx
This PR adds a check so that we don't show the choropleth property picker when the relevant fields are not present
Fixes issue [MAP-718](https://linear.app/commonknowledge/issue/MAP-718/choropleth-property-cant-be-picked)
=> Only show choropleth property picker when fields are present

hub/management/commands/export_areas_as_sql.py
Adds a command, `export_areas_as_sql`, that iterates through `AreaType` and `Area` instances, and outputs them to a raw SQL file. The output SQL does not include any references to `id` columns, so can be used to populate existing databases where IDs may be different.
=> feat: add export_areas_as_sql command

nextjs/src/app/reports/[id]/(components)/MembersListPointMarkers.tsx
This PR adjusts the zoom level for the map and replaces the circle images with mapbox circles (ensures they are anchor centrally to the coordinates)
Addresses issues [MAP-603](https://linear.app/commonknowledge/issue/MAP-603/show-map-markers-at-an-appropriate-zoom-level) and [MAP-727](https://linear.app/commonknowledge/issue/MAP-727/position-markers-at-centre-of-coordinates-not-above-or-below)
=> Adjust zoom level for map and replace circle images with mapbox circles

hub/graphql/types/model_types.py, hub/models.py, hub/parsons/action_network/action_network.py, hub/tests/test_sources.py
Running the tests added records to Action Network. This was causing the Action Network group to have 1000s of records, which made the tests very slow.
This PR makes the Action Network tests use existing records.
This PR also fixes a couple of bugs:
1. The Action Network client was always fetching one more page than it needed to;
2. Analytics.imported_data_by_area was not fixed for admin_districts
=> feat: dont create actionnetwork rows in test_sources as they cant be deleted

hub/graphql/types/model_types.py, nextjs/src/components/puck/config/blocks/GridRow/index.tsx
This PR fixes the discrepancy between the display of the child columns in the Grid Row block in the editor and on the published page. 
The block is now using renderDropZone and has a div wrapper around each column to preserve the layout between the editor and page.
Addresses issue [CC-205](https://linear.app/commonknowledge/issue/CC-205/fix-grid-columns-layout-shift-between-editor-and-public-page)
1. Run locally
2. Go to [http://localhost:3000/hub/editor ](http://localhost:3000/hub/editor)
3. Add a grid row block
4. Observe that on the published page the columns are displayed in the same way as in the editor
Normal deployment process
=> Fix layout shift between hub editor and published page in grid column block

hub/graphql/types/model_types.py, nextjs/src/app/reports/[id]/(components)/ReportProvider.tsx, nextjs/src/app/reports/[id]/(components)/ReportVisualisation.tsx
This PR ensures that wrong field values in the choropleth API don't produce weird results, and tries to funnel the map to the right kind of field values that make sense for a given data source. This will produce fewer instances of "there's nothing on the map" or "this doesn't make sense" without manual configuration.
=> Fix count / choropleth field selection

hub/data_imports/geocoding_config.py, hub/graphql/dataloaders.py, hub/graphql/types/model_types.py, hub/models.py, hub/tests/fixtures/geocoding_cases.py, hub/tests/test_external_data_source_parsers.py, local_intelligence_hub/settings.py
Part of the work required for the data pipeline V2: https://linear.app/commonknowledge/issue/MAP-973/planning-for-data-import-pipeline-v2
This adds a new Geocoder: `AREA_CODE_GEOCODER_V2`. To enable it, the geocoding config must have only one element, with the `"type"` set to `"area_code"`.
This Geocoder uses dataloaders to ensure maximum parallelisation.
Add an AreaData source, where each row is identified to an area by code. Set up the geocoding_config to look something like:
```{
"type": "AREA",
"components": [
{
"type": "area_code",
"field": "oa21cd",
"value": "",
"metadata": {
"lih_area_type__code": "OA21"
}
}
]
}```
Then run the import on the data source.
=> feat: add AREA_CODE high performance geocoding

hub/graphql/types/stats.py, hub/models.py, utils/statistics.py
Postgres has a column name limit of 60 characters – this PR checks if a column over 60 characters is going to be generated, and if so, truncates it and adds a hash of 8 characters at the end.
=> fix: give materialized view columns a hash if necessary to ensure uniqueness

hub/data_imports/geocoding_config.py, hub/tests/test_statistics.py, utils/postgis_geocoder.py
When geocoding an Area, uses `area.polygon.point_on_surface` instead of `centroid` to return a point that is definitely inside the area. Also makes sure that the `postcode_data` always uses the `Area` that was matched by code, over the geocoding results.
https://linear.app/commonknowledge/issue/MAP-1042/fix-output-area-postgis-geocoding-issue
=> fix: correct sample_point used for postgis geocoding
